# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\main\python\gui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(308, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages.setEnabled(True)
        self.pages.setAutoFillBackground(False)
        self.pages.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pages.setObjectName("pages")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.launchBox = QtWidgets.QCheckBox(self.groupBox)
        self.launchBox.setStyleSheet("font: italic 8pt \"Arial\";")
        self.launchBox.setChecked(True)
        self.launchBox.setObjectName("launchBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.launchBox)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.resetBox = QtWidgets.QCheckBox(self.groupBox)
        self.resetBox.setText("")
        self.resetBox.setChecked(True)
        self.resetBox.setObjectName("resetBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.resetBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.configList = QtWidgets.QComboBox(self.groupBox)
        self.configList.setObjectName("configList")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.configList)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dxlevelList = QtWidgets.QComboBox(self.groupBox)
        self.dxlevelList.setObjectName("dxlevelList")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dxlevelList)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.connectionType = QtWidgets.QComboBox(self.groupBox)
        self.connectionType.setObjectName("connectionType")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.connectionType)
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connectionSpeed = QtWidgets.QLabel(self.frame)
        self.connectionSpeed.setObjectName("connectionSpeed")
        self.horizontalLayout_2.addWidget(self.connectionSpeed)
        self.refreshConnectionSpeed = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshConnectionSpeed.sizePolicy().hasHeightForWidth())
        self.refreshConnectionSpeed.setSizePolicy(sizePolicy)
        self.refreshConnectionSpeed.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.refreshConnectionSpeed.setObjectName("refreshConnectionSpeed")
        self.horizontalLayout_2.addWidget(self.refreshConnectionSpeed)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.frame)
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.refreshRate = QtWidgets.QLineEdit(self.frame_2)
        self.refreshRate.setEnabled(False)
        self.refreshRate.setStyleSheet("border-color: rgba(255, 255, 255, 0);")
        self.refreshRate.setMaxLength(3)
        self.refreshRate.setReadOnly(False)
        self.refreshRate.setObjectName("refreshRate")
        self.horizontalLayout_3.addWidget(self.refreshRate)
        self.toggleRefreshRate = QtWidgets.QCheckBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleRefreshRate.sizePolicy().hasHeightForWidth())
        self.toggleRefreshRate.setSizePolicy(sizePolicy)
        self.toggleRefreshRate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toggleRefreshRate.setText("")
        self.toggleRefreshRate.setChecked(True)
        self.toggleRefreshRate.setObjectName("toggleRefreshRate")
        self.horizontalLayout_3.addWidget(self.toggleRefreshRate)
        self.autoRefreshRate = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoRefreshRate.sizePolicy().hasHeightForWidth())
        self.autoRefreshRate.setSizePolicy(sizePolicy)
        self.autoRefreshRate.setObjectName("autoRefreshRate")
        self.horizontalLayout_3.addWidget(self.autoRefreshRate)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.frame_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.pages.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBox_3)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBox_4)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.pages.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.pages.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.istate = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istate.sizePolicy().hasHeightForWidth())
        self.istate.setSizePolicy(sizePolicy)
        self.istate.setWordWrap(True)
        self.istate.setObjectName("istate")
        self.verticalLayout_7.addWidget(self.istate)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.pages.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.page_5)
        self.label_8.setStyleSheet("font: 16pt \"Arial\";\n"
"color: rgb(0, 238, 139);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.label_15 = QtWidgets.QLabel(self.page_5)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.backupPath = QtWidgets.QLineEdit(self.page_5)
        self.backupPath.setEnabled(True)
        self.backupPath.setReadOnly(True)
        self.backupPath.setObjectName("backupPath")
        self.horizontalLayout_4.addWidget(self.backupPath)
        self.copyBackupPath = QtWidgets.QPushButton(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyBackupPath.sizePolicy().hasHeightForWidth())
        self.copyBackupPath.setSizePolicy(sizePolicy)
        self.copyBackupPath.setMaximumSize(QtCore.QSize(40, 16777215))
        self.copyBackupPath.setObjectName("copyBackupPath")
        self.horizontalLayout_4.addWidget(self.copyBackupPath)
        self.openBackupPath = QtWidgets.QPushButton(self.page_5)
        self.openBackupPath.setMaximumSize(QtCore.QSize(40, 16777215))
        self.openBackupPath.setObjectName("openBackupPath")
        self.horizontalLayout_4.addWidget(self.openBackupPath)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.line_3 = QtWidgets.QFrame(self.page_5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_8.addWidget(self.line_3)
        self.label_14 = QtWidgets.QLabel(self.page_5)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.configuratedPath = QtWidgets.QLineEdit(self.page_5)
        self.configuratedPath.setReadOnly(True)
        self.configuratedPath.setObjectName("configuratedPath")
        self.horizontalLayout_5.addWidget(self.configuratedPath)
        self.copyConfiguratedPath = QtWidgets.QPushButton(self.page_5)
        self.copyConfiguratedPath.setMaximumSize(QtCore.QSize(40, 16777215))
        self.copyConfiguratedPath.setObjectName("copyConfiguratedPath")
        self.horizontalLayout_5.addWidget(self.copyConfiguratedPath)
        self.openConfiguratedPath = QtWidgets.QPushButton(self.page_5)
        self.openConfiguratedPath.setMaximumSize(QtCore.QSize(40, 16777215))
        self.openConfiguratedPath.setObjectName("openConfiguratedPath")
        self.horizontalLayout_5.addWidget(self.openConfiguratedPath)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.pages.addWidget(self.page_5)
        self.verticalLayout_2.addWidget(self.pages)
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prevButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.prevButton.setMinimumSize(QtCore.QSize(70, 0))
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout.addWidget(self.prevButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.nextButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.nextButton.setMinimumSize(QtCore.QSize(70, 0))
        self.nextButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.verticalLayout_2.addWidget(self.horizontalFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 308, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "configuraTed"))
        self.groupBox.setTitle(_translate("MainWindow", "1 - Config"))
        self.label_3.setText(_translate("MainWindow", "Launch Options:"))
        self.launchBox.setText(_translate("MainWindow", "(steam will be restarted)"))
        self.label.setText(_translate("MainWindow", "Reset TF2:"))
        self.label_2.setText(_translate("MainWindow", "Config:"))
        self.label_4.setText(_translate("MainWindow", "DirectX Version:"))
        self.label_9.setText(_translate("MainWindow", "Refresh Rate:"))
        self.label_10.setText(_translate("MainWindow", "Connection Type:"))
        self.label_12.setText(_translate("MainWindow", "Connection Speed:"))
        self.connectionSpeed.setText(_translate("MainWindow", "unknown"))
        self.refreshRate.setInputMask(_translate("MainWindow", "990"))
        self.autoRefreshRate.setText(_translate("MainWindow", "Auto"))
        self.groupBox_2.setTitle(_translate("MainWindow", "2 - Extras"))
        self.label_5.setText(_translate("MainWindow", "No Hats Mod:"))
        self.label_6.setText(_translate("MainWindow", "No explosion smoke script:"))
        self.label_7.setText(_translate("MainWindow", "Particle Limitation Pack:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "3 - Plugins"))
        self.groupBox_4.setTitle(_translate("MainWindow", "4 - Installation"))
        self.istate.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Click install to install the new config!</p><p align=\"center\">TF2 may start and close during the installation.</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Success!"))
        self.label_15.setText(_translate("MainWindow", "Your old config files are located at:"))
        self.copyBackupPath.setText(_translate("MainWindow", "Copy"))
        self.openBackupPath.setText(_translate("MainWindow", "Open"))
        self.label_14.setText(_translate("MainWindow", "Your new config files are located at:"))
        self.copyConfiguratedPath.setText(_translate("MainWindow", "Copy"))
        self.openConfiguratedPath.setText(_translate("MainWindow", "Open"))
        self.prevButton.setText(_translate("MainWindow", "Previous"))
        self.nextButton.setText(_translate("MainWindow", "Next"))

